name: CI Quality

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'CHANGELOG.md'
      - '.github/ISSUE_TEMPLATE.md'
      - '.github/PULL_REQUEST_TEMPLATE.md'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm test

      - name: AI Engine Smoke Test
        run: npm run test:ai || echo "AI engine test skipped (requires creds)"

      - name: Security Audit
        run: npm audit --production --audit-level=moderate || echo "Audit warnings (non-blocking)"
